name: Cloudflare R2 Upload
description: Upload directory to Cloudflare R2
author: Okkema Labs <correos@okkema.org>
branding:
  icon: upload-cloud
  color: orange
inputs:
  account_id:
    description: Cloudflare account id
    required: true
  r2_access_key:
    description: Cloudflare R2 access key
    required: true
  r2_secret_key:
    description: Cloudflare R2 secret key
    required: true
  r2_bucket:
    description: Cloudflare R2 bucket name
    required: true
  source_dir:
    required: true
    description: Source directory to upload
  destination_dir:
    required: false
    default: /
    description: Destination directory for upload
runs:
  using: node16
  main: dist/index.js
